### ISSUE TITLE
Please ADD "date"  feature that shows under the name!

### ISSUE THREAD

**Issue by weilinzung** [simonneutert/google-maps-reviews#1]
Please ADD "date"  feature that shows under the name!

**Comment by simonneutert** [comment]
simply modify the html yourself, in this line: https://github.com/simonneutert/google-maps-reviews/blob/9070b573a8d31fec3458e36a81ae6b2e017b5786/google-maps-reviews.js#L111

**Comment by simonneutert** [comment]
If I find the time, I might add a function and will tell you here.

**Comment by weilinzung** [comment]
ok, hopefully would be soon. thanks! @simonneutert

**Comment by simonneutert** [comment]
"show_date" option has been added, what you make of it - that is completely up to you ✌️

**Comment by weilinzung** [comment]
Thanks!  @simonneutert 

By the way, I can't get it running, can you make a demo page?

Also, would be nice to add the feature to here: https://github.com/simonneutert/google-maps-reviews

It keep giving me "googlePlaces is not defined".
https://jsfiddle.net/zysxm6cn/9/

**Comment by simonneutert** [comment]
There is a demo in this repository. Read the instructions well and you will be golden. You need to understand the basics of HTML, CSS and JavaScript of course - good luck!
