### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'places')

### ISSUE THREAD

**Issue by alby270** [simonneutert/google-maps-reviews#12]
When I tried to get this working I got this error:

Uncaught TypeError: Cannot read properties of undefined (reading 'places')

I have added the Google places api key before, so I'm not sure what the reason is...

**Comment by agoyal118** [comment]
I'm getting the same error

**Comment by simonneutert** [comment]
i will take a look what's going on in the coming days, can't promise though

**Comment by simonneutert** [comment]
checked it, released v0.3.0 was able to display last 5 reviews, get back with a few details describing what you've tried so far if the error isn't gone for both of you
