### ISSUE TITLE
Google author_name change to "A Google User"?

### ISSUE THREAD

**Issue by weilinzung** [simonneutert/google-maps-reviews#2]
jut notice all of the author names changed to `A Google User`.

**Comment by simonneutert** [comment]
please describe better and add a screenshot by copy and pasting here 👍

**Comment by weilinzung** [comment]
just the review author name changed to `A Google User`. Not sure if the Google API updated.

**Comment by weilinzung** [comment]
here is the screenshot: https://image.ibb.co/jCefZe/Screen_Shot_2018_09_04_at_10_59_09_AM.png

**Comment by simonneutert** [comment]
Try another location, please.

**Comment by weilinzung** [comment]
`ChIJreEXi4FZwokR_ygs7wh2fTk` same issue!

**Comment by simonneutert** [comment]
If a user chooses to remain anonymous then `A Google User` is rendered by default. I may add a function for a custom text.

See: https://developers.google.com/places/web-service/details

**Comment by weilinzung** [comment]
Is that a new feature just added to Google Place API, before it's fine? 

And Google Page is fine by rendering those names without `A Google User`: https://www.google.ca/search?q=Ivan+Ramen%2C+Clinton+Street%2C+New+York%2C+NY%2C+USA&oq=Ivan+Ramen%2C+Clinton+Street%2C+New+York%2C+NY%2C+USA&aqs=chrome..69i57.785j0j4&sourceid=chrome&ie=UTF-8#lrd=0x89c259818b17e1ad:0x397d7608ef2c28ff,1,,,

Also, I double check some of the WordPress plugins which they are all using `author_name` string, and those are fine too.

**Comment by simonneutert** [comment]
@weilinzung this is a new feature as far as I can tell

**Comment by simonneutert** [comment]
@weilinzung see the updated readme and update to v0.0.20 

new settings/options were added
``` javascript
replace_anonymous: false, // do not replace anonymous author_name from JSON
anonymous_name: "A Google User", // Google's default value depending on language used (en: "A Google User")
anonymous_name_replacement: "remains anonymous", // replacement for default (never shortens)
```

thank you for supporting this project 🙏

**Comment by weilinzung** [comment]
@simonneutert  Just one small thing, I think would be good to just replace random names, because if I replaced to "Test" then all the reviews look like from one person.

**Comment by simonneutert** [comment]
@weilinzung I respect other people's decisions. You may pass a function that shuffles an array to the anonymous_name_replacement - this could work. I personally do not consider implementing this as a feature.
