### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by macogo** [simonneutert/google-maps-reviews#3]
google-maps-reviews
webpack:/external "google-maps-reviews":1
> 1 | module.exports = require("google-maps-reviews");
![Capture](https://user-images.githubusercontent.com/9974125/61516388-7555ef00-aa37-11e9-951d-04b372309068.PNG)

**Comment by macogo** [comment]
when I import this component in my project then this error occurred

**Comment by simonneutert** [comment]
do you have node and npm setup correctly?

if you need the jquery based version, check this out:  
https://github.com/simonneutert/jquery-google-reviews/

**Comment by macogo** [comment]
actually, I use yarn to add this module.,cause something goes wrong when I use npm.   Is it matter?

**Comment by macogo** [comment]
I don't want to use the  jquery based version. This version is exactly the one that I want.

**Comment by ravenwits** [comment]
I also get this error ./

**Comment by simonneutert** [comment]
please, check how it was done in the demo

https://github.com/simonneutert/google-maps-reviews/blob/master/demo_with_webpack/src/index.js
