### ISSUE TITLE
ratings in a slider

### ISSUE THREAD

**Issue by eberhardst** [simonneutert/google-maps-reviews#4]
Hallo Simon,
do you have any ideas how I can display the ratings in a slider?
best regards
Eberhard

**Comment by simonneutert** [comment]
:de: 
Hallo Eberhard,

man müsste die Sterne Funktion gegen einen Slider tauschen. Und einen Wert in den Optionen abfragen was/wie dargestellt werden soll. Magst du das machen? Ansonsten lass uns mal austauschen wie wir das anstellen. Ich finde weitere Darstellungsmöglichkeiten prinzipiell sehr sinnvoll.

---
:gb: :us: 
Hey Eberhard,

one would need to add slider rendering next to the render stars functions. then add a value to the options, asking how to display rating. can you do it?

**Comment by simonneutert** [comment]
closed due to inactivity
