### ISSUE TITLE
Minimum reviews to display

### ISSUE THREAD

**Issue by risingisland** [simonneutert/google-maps-reviews#7]
Hello Simon. Wonderful script.

I am having a small issue with displaying more than 5 reviews.
No matter what number I set, it only displays 5 or less.
Also, is it possible to randomize the reviews being displayed?

**Comment by simonneutert** [comment]
This is what google gives us, afaik. If you like, check google's docs for the maps api. My schedule is rather packed 🤯

I am looking forward to hearing from you 💪 
cheers
